spring:
  profiles:
    active: dev
  application:
    name: core-service

  data:
    web:
      pageable:
        default-page-size: 25
        one-indexed-parameters: true
        max-page-size: 2000
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
#logging:
#  config: classpath:logback-spring.xml

fatpigeon:
  foreEndUrl: http://localhost:8080